# Generated by Django 3.0.2 on 2020-01-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('away_team', models.CharField(max_length=50)),
                ('away_rest', models.IntegerField()),
                ('home_team', models.CharField(max_length=50)),
                ('home_rest', models.IntegerField()),
                ('arena', models.CharField(max_length=50)),
            ],
        ),
    ]
